spring:
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 'root'
